audit_header: false
title: San Diego Real Estate Video Blog with Scott Voak
description: Our mission at Voak Homes is to be your best resource for San Diego real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Voak Homes, your professional San Diego Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Local Vendors
    url: /local-vendors/

client:
  name: Scott Voak
  title:
  license_number:
  about_markdown: |
    Scott has distinguished himself as a multiple 5-Star Award Winner and best selling real estate author. He believes that the higher standard of service expected from and provided by Sotheby’s International Realty agents extends to all homeowners, not just those who own luxury or estate homes.

    He believes the two most important factors he contributes that helps secure the highest price for his sellers are his commitment to marketing and his negotiating skills.

    Being with Sotheby's International Realty provides tools for local and international marketing that other agents just don't have. But, it's not only having the tools, but it's also the commitment to use them and invest more money than other agents into the marketing of his clients' homes. To this end, he uses not one, but three sets of professionals to create the photos to be used for marketing as well as a 3D tour and live video that can be used both with the MLS and to strategically market the home on social media.

    Once offers are received, Scott has designed a system to get his sellers the highest possible price. This system was built using knowledge from Scott's negotiating deals in the hi-tech industry and as a corporate CEO dealing with the Teamsters Union - in addition to the thousands of real estate sellers he has helped.
  market: San Diego
  brand: Voak Homes
  brokerage: Pacific Sotheby's International Realty
  address: 16710 Bernardo Center Dr. San Diego, CA 92128
  phone: 888-311-6311
  phone_type:
  phone2:
  phone2_type:
  email: scott@VoakHomes.com
  url: http://www.VoakHomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://cloudcma.com/api_widget/3bb9df8a498052ee2a3ff929ae0db2fe/show?post_url=cloudcma.com&source_url=ua+
  second_CTA_text: Home Search
  second_CTA_URL: http://www.voakhomes.com/search.html

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your San Diego Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://cloudcma.com/api_widget/3bb9df8a498052ee2a3ff929ae0db2fe/show?post_url=cloudcma.com&source_url=ua+

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a San Diego Home?"
    CTA_text2: "Search the entire MLS for your San Diego home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.voakhomes.com/search.html

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/voakhomesrealestate
  linkedin_url: https://www.linkedin.com/in/scottvoak
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UCO5-ZNxzrbMyHiJdXzFAM8w
  twitter_url: https://twitter.com/scottvoak
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'San Diego Real Estate Podcast with Scott Voak'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Diego Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Voak Homes - your professional San Diego Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Diego, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Scott Voak'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: San Diego Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#002b5c'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
